version: '3.8'

services:
  # Main OpenManus AI Platform
  openmanus:
    build:
      context: .
      target: production
    container_name: openmanus-ai
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - DATABASE_URL=postgresql://openmanus:${DB_PASSWORD:-openmanus123}@postgres:5432/openmanus
      - REDIS_URL=redis://redis:6379/0
      - HTTPS=${HTTPS:-false}
    volumes:
      - ./workspace:/app/workspace
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./config:/app/config
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: openmanus-postgres
    environment:
      - POSTGRES_DB=openmanus
      - POSTGRES_USER=openmanus
      - POSTGRES_PASSWORD=${DB_PASSWORD:-openmanus123}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openmanus -d openmanus"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: openmanus-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # NGINX Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: openmanus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - openmanus
    restart: unless-stopped
    profiles:
      - production



  # Development services
  openmanus-dev:
    build:
      context: .
      target: development
    container_name: openmanus-ai-dev
    ports:
      - "5000:5000"
      - "5678:5678"  # Debug port
    environment:
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=postgresql://openmanus:${DB_PASSWORD:-openmanus123}@postgres:5432/openmanus
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
      - ./workspace:/app/workspace
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    profiles:
      - development

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: openmanus-network
    driver: bridge